### ISSUE TITLE
How would I use this with a user model extending AbstractBaseUser

### ISSUE THREAD

**Issue by guyjacks** [amitu/django-encrypted-id#12]
I have a model like this:

```
class User(AbstractBaseUser):
    ...
```

How would you recommend I modify it to use django-encrypted-id since I can't do

```
class User(EncryptedIDModel)
    ...
```

**Comment by jatinderjit** [comment]
You can use [multiple inheritance](https://docs.python.org/3/tutorial/classes.html#multiple-inheritance).
```python
class User(AbstractBaseUser, EncryptedIDModel):
    ...
```
